export const DataSample = {
    table: {
        heading: [
            "No",
            "Foto Profil",
            "Nama",
            "NIS",
            "NISN",
            "Kelas",
            "Tempat Lahir",
            "Tanggal Lahir",
            "Email",
            "Nomor Telepon",
            "Jenis Kelamin",
            "Alamat",
            "Agama",
            "Opsi",
        ],
        data: [
            {
                foto_profil: null,
                nama: "Ahmad Fauzan",
                nis: "21221314",
                nisn: "0056622849",
                kelas: "XII RPL 1",
                tempat_lahir: "Tasikmalaya",
                tanggal_lahir: "15 Agustus 2005",
                email: "ahmadfzn2005@gmail.com",
                nomor_tlp: "+6287846775109",
                jenis_kelamin: "Laki-Laki",
                alamat: "Jl.Cinusa Girang",
                agama: "Islam",
            },
            {
                foto_profil: "/img/lusi.jpeg",
                nama: "Lusi Kuraisin",
                nis: "21221327",
                nisn: "0056622848",
                kelas: "XII RPL 1",
                tempat_lahir: "Tasikmalaya",
                tanggal_lahir: "25 Agustus 2005",
                email: "kuraisinlusi@gmail.com",
                nomor_tlp: "+6283141636141",
                jenis_kelamin: "Perempuan",
                alamat: "Jl.Sanding Timur",
                agama: "Islam",
            },
        ],
    },
};
